baseURL = "https://blog.edmason.co.uk"
title = "Ed Mason"
theme = "etch"
languageCode = "en-GB"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitInfo = true
enableEmoji = true

[params]
  description = "My blog"
  copyright = "Copyright © 2024 Ed Mason"
  notFound = "404 Page Not Found. Apologies!"
  dark = "auto"
  highlight = true

[params.staticman]
    endpoint = "https://staticman-qihs.onrender.com/v2/entry"
    username = "edapm"
    repository = "website"
    branch = "main" 

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:year/:month/:day/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = 'keywords'
  pattern = ''
  toLower = false
  type = 'basic'
  weight = 100
[[related.indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = 'date'
  pattern = ''
  toLower = false
  type = 'basic'
  weight = 10
[[related.indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = 'tags'
  pattern = ''
  toLower = false
  type = 'basic'
  weight = 80