baseURL = "https://edwardmason.vercel.app"
title = "Ed Mason"
theme = "etch"
languageCode = "en-GB"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitInfo = true
enableEmoji = true

[params]
  description = "My website"
  copyright = "Copyright © 2023 Ed Mason"
  notFound = "404 Page Not Found. Apologies!"
  dark = "auto"
  highlight = true

[params.staticman]
    endpoint = "https://staticman-qihs.onrender.com/v2/entry"
    username = "edapm"
    repository = "website"
    branch = "main" 

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:year/:month/:day/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
